name: Quick Test
on: [push, pull_request]
permissions:
  contents: read

jobs:

    flake8:
      name: Linter
      if: "!contains(github.event.head_commit.message, 'ci skip all')"
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install flake8
        run: pip3 install -r requirements.txt
      - name: Run flake8
        run: flake8 .